mrs_uav_controllers_cac:

  se3_controller_CAC:

    se3:

      default_gains:

        # Gains in this section SHOULD NOT BE CHANGED, since they are not used most of the times.
        # Gains which are actually used are in the mrs_uav_manager package under the gain_manager configs
        pendulum:
          kqcac_xy: 8.0
          kqcac_z: 8.0
          kqcac_dot_xy: 4.5
          kqcac_dot_z: 4.5

        horizontal:
          kp: 10.0
          kv: 30.0
          ka: 1.0

          attitude:
            kq: 5.0

          kib: 0.1
          kib_lim: 10.0

          kiw: 0.1
          kiw_lim: 10.0

        vertical:
          kp: 15.0
          kv: 8.0
          ka: 1.0

        attitude:
          kq_roll_pitch: 3.0
          kq_yaw: 2.0

        mass_estimator:
          km: 1.0
          km_lim: 3.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

      attitude_rate_gains:
        kw_roll_pitch: 4.0
        kw_yaw: 4.0

      rampup:
        enabled: true
        speed: 0.75 # [1/s]

      gain_filtering:

        rate: 10.0 # [Hz]

        perc_change_rate: 1.0 # [100%/s]
        min_change_rate: 0.2 # perc of the difference

        # gains can be muted by the tracker by this factor
        # gains are also muting just after activation
        gain_mute_coefficient: 0.5 # [-]
