hw_interface_plugin: "mrs_simulator_api_plugin/Api"

gnss:
  utm_zone: "32T"
  utm_x: 465710.758973
  utm_y: 5249465.43086
  amsl: 340.0

# determines if offboard can be switched on
input_timeout: 1.0 # [s]

input_mode:
  actuators:             false
  control_group:         false
  attitude_rate:         true
  attitude:              true
  acceleration_hdg_rate: false
  acceleration_hdg:      false
  velocity_hdg_rate:     false
  velocity_hdg:          false
  position:              false

  feedforward: true

outputs:
  distance_sensor:      true
  gnss:                 true
  rtk:                  false
  imu:                  false
  altitude:             true
  magnetometer_heading: true
  rc_channels:          false
  battery_state:        false
  position:             true
  orientation:          true
  velocity:             true
  angular_velocity:     true
  odometry:             false
  ground_truth:         true
